# Data path
metadata: "accessions_PE.txt"

# Output paths
datadir: "data/"
resdir: "results/"
logdir: "logdir/"
# Snakefile location
snkpth: "Snakefile_procdata_PE_v.0.2"


# Reference files
GENOME_FA: "/proj/snic2020-16-205/private/nbis5433/fa/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa"


# Adapter for trimming
adapterFWD: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
adapterREV: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"


# Parameters for calculation of normalised coverage tracks
efGenomeSize: "12400000"
