# Data path

# Output paths
datadir: "data/"
resdir: "results/"
logdir: "logdir/"
# Snakefile location
snkpth: "Snakefile_procdata_fastq_PE_v.0.1"

#W303 reference from geneBank

# Reference files
GENOME_FA: "/proj/epi2022/nobackup/private/agata/mnaseseq/reference/w303/GCA_002163515.1_ASM216351v1_genomic.fna"

# Parameters for calculation of normalised coverage tracks
efGenomeSize: "12400000"
